name: stagess_reverse_proxy
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none 

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  stagess_common:
    path: ../stagess_common
  logging: ^1.3.0

dependency_overrides:
  enhanced_containers_foundation:
    path: ../external/enhanced_containers/plugins/enhanced_containers_foundation

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
