name: stagess_admin
description: "The admin interface of Stagess"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  collection: ^1.16.0
  provider: ^6.0.3
  firebase_core: ^4.2.1
  go_router: ^16.2.4
  flutter_form_builder: ^10.0.1
  intl: ^0.20.2
  uuid: ^4.5.1
  file_picker: ^10.2.0
  crcrme_material_theme:
    path: ../external/crcrme_material_theme
  stagess_common:
    path: ../stagess_common
  stagess_common_flutter:
    path: ../stagess_common_flutter
  logging: ^1.3.0

dependency_overrides:
  enhanced_containers_foundation:
    path: ../external/enhanced_containers/plugins/enhanced_containers_foundation
  enhanced_containers:
    path: ../external/enhanced_containers/


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
